- uses: lowlighter/metrics@latest
  with:
    token: ${{ secrets.METRICS_TOKEN }}

    user: vops  
    template: classic
    base: header, activity, community, repositories, metadata
    
   
    plugin_isocalendar: yes
    plugin_languages: yes
    plugin_stars: yes
