name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   
  push:
    branches: ["main"]
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
 
          token: ${{ secrets.METRICS_TOKEN }}

        
          user: ironweb10
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          config_twemoji: yes
          config_order: base.header, base.activity+community, base.repositories, base.metadata, isocalendar, languages, stars, habits, achievements

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_repositories: yes
          plugin_repositories_featured: ironweb10/metrics, ironweb10/portfolio

          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 6
          plugin_lines_history_limit: 12

          plugin_traffic: yes

       
          config_padding: 12, 8
          config_display: large
          config_octicon: yes
          config_base: header, repositories, metadata
          config_output: metrics.svg
