name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   
  push:
    branches: ["main"]
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}


          user: ironweb10
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          config_twemoji: yes
          config_display: large
          config_octicon: yes
          config_padding: 12, 8
          config_output: metrics.svg


          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_repositories: yes
          plugin_traffic: yes
